import numpy as np
from scipy.spatial.distance import pdist, squareform
from scipy.spatial import ConvexHull, distance_matrix
from miniBSE.constants import (
    HA_TO_EV, ANG_PER_BOHR, BOHR_PER_ANG,
    IMAGE_CHARGE_CONST_EV_ANG, BRUS_KINETIC_EV_ANG2, VDW_SURFACE_ANG
)

# Atomic Hardness values (eta) in eV. 
# Used for the Ohno-Klopman damping in the Coulomb kernel.
HARDNESS_DICT = {
    'h': 6.4299, 'he': 12.5449, 'li': 2.3746, 'be': 3.4968, 'b': 4.619, 'c': 5.7410,
    'n': 6.8624, 'o': 7.9854, 'f': 9.1065, 'ne': 10.2303, 'na': 2.4441, 'mg': 3.0146,
    'al': 3.5849, 'si': 4.1551, 'p': 4.7258, 's': 5.2960, 'cl': 5.8662, 'ar': 6.4366,
    'k': 2.3273, 'ca': 2.7587, 'sc': 2.8582, 'ti': 2.9578, 'v': 3.0573, 'cr': 3.1567,
    'mn': 3.2564, 'fe': 3.3559, 'co': 3.4556, 'ni': 3.555, 'cu': 3.6544, 'zn': 3.7542,
    'ga': 4.1855, 'ge': 4.6166, 'as': 5.0662, 'se': 5.4795, 'br': 5.9111, 'kr': 6.3418,
    'rb': 2.1204, 'sr': 2.5374, 'y': 2.6335, 'zr': 2.7297, 'nb': 2.8260, 'mo': 2.9221,
    'tc': 3.0184, 'ru': 3.1146, 'rh': 3.2107, 'pd': 3.3069, 'ag': 3.4032, 'cd': 3.4994,
    'in': 3.9164, 'sn': 4.3332, 'sb': 4.7501, 'te': 5.167, 'i': 5.5839, 'xe': 6.0009,
    'cs': 0.6829, 'ba': 0.9201, 'la': 1.1571, 'ce': 1.3943, 'pr': 1.6315, 'nd': 1.8686,
    'pm': 2.1056, 'sm': 2.3427, 'eu': 2.5798, 'gd': 2.8170, 'tb': 3.0540, 'dy': 3.2912,
    'ho': 3.5283, 'er': 3.7655, 'tm': 4.0026, 'yb': 4.2395, 'lu': 4.4766, 'hf': 4.7065,
    'ta': 4.9508, 'w': 5.1879, 're': 5.4256, 'os': 5.6619, 'ir': 5.900, 'pt': 6.1367,
    'au': 6.3741, 'hg': 6.6103, 'tl': 1.7043, 'pb': 1.9435, 'bi': 2.1785, 'po': 2.4158,
    'at': 2.6528, 'rn': 2.8899, 'fr': 0.9882, 'ra': 1.2819, 'ac': 1.3497, 'th': 1.4175,
    'pa': 1.9368, 'u': 2.2305, 'np': 2.5241, 'pu': 3.0436, 'am': 3.4169, 'cm': 3.4050,
    'bk': 3.9244, 'cf': 4.2181, 'es': 4.5116, 'fm': 4.8051, 'md': 5.0100, 'no': 5.3926,
    'lr': 5.4607
}

# =====================================================================
# MATERIAL DATABASE (2026 BENCHMARKS)
# =====================================================================
# Updated Format: (eps_inf, Bohr_diam_A, lattice_A, gap_exp_eV, eps_static, m_eff, E_LO_eV, 
#                  gap_pbe_bulk_eV, gap_gw_bulk_eV, 
#                  R_mono_A, pbe_homo_mono, pbe_lumo_mono, gw_homo_mono, gw_lumo_mono)
# Note: PBE and GW gaps are SCALAR RELATIVISTIC (No SOC).
# Bulk values are taken from the literature. Monomer values are computed with cp2k : DZVP-RI/GTH/PBE then GW
# Monomer values are computed using PBE0 + GW for the scissor to correct the PBE DFT gap in the second last column. 
# The R0 monomer is computed using convex hull on the relaxed structure
# Inverted gap systems (InAs, InSb, HgSe, HgTe) use negative PBE values to ensure correct scissor scaling.

# Automatically generated by CP2K Data Extractor
MATERIAL_DB = {
    "CS3BI2BR9": (3.9, 24.0, 8.01, 2.55, 11.7, 0.57, 0.021, 3.33, 3.65, 7.850, -5.5000, -1.8500, -7.2000, 0.1500),
    # Halide Perovskites (Cubic Phase Benchmarks)
    "CSPBCL3": (4.0, 25.0, 5.6, 3.0, 20.0, 0.15, 0.022, 2.45, 3.65, 7.604, -4.7512, -1.5076, -6.5706, 0.3314),
    "CSPBBR3": (4.8, 35.0, 5.83, 2.3, 25.0, 0.12, 0.018, 1.85, 2.85, 7.9149, -4.7779, -1.6961, -6.3775, 0.4555),
    "CSPBI3": (5.1, 60.0, 6.2, 1.73, 30.0, 0.1, 0.015, 1.55, 2.45, 8.3726, -4.4874, -1.7988, -5.6323, 0.3893),
    "MAPBI3": (6.5, 45.0, 6.27, 1.55, 30.0, 0.1, 0.015, 1.55, 2.5),
    "FAPBI3": (6.2, 50.0, 6.36, 1.48, 28.0, 0.1, 0.015, 1.45, 2.35),

    # II–VI Semiconductors
    "ZNS": (5.1, 25.0, 5.41, 3.6, 8.9, 0.28, 0.043, 2.11, 3.73, 4.8204, -6.6591, -3.208, -8.2883, -1.0303),
    "ZNSE": (5.9, 38.0, 5.67, 2.7, 8.6, 0.17, 0.031, 1.25, 2.76, 4.9394, -6.4914, -3.1993, -7.9032, -1.063),
    "ZNTE": (6.7, 52.0, 6.1, 2.26, 9.8, 0.12, 0.026, 1.18, 2.35, 5.1907, -5.789, -2.8062, -7.0003, -0.901),
    "CDS": (5.4, 30.0, 5.82, 2.42, 8.9, 0.16, 0.037, 1.14, 2.55, 5.1533, -6.598, -3.88, -8.2128, -1.8481),
    "CDSE": (6.2, 56.0, 6.05, 1.74, 9.5, 0.13, 0.026, 0.64, 1.91, 5.2578, -6.4196, -3.7852, -7.8177, -1.7884),
    "CDTE": (7.1, 73.0, 6.48, 1.44, 10.2, 0.1, 0.021, 0.61, 1.62, 5.4433, -5.7978, -2.9767, -6.9951, -0.9143),
    "HGS": (11.3, 50.0, 5.85, 0.5, 13.0, 0.2, 0.03, 0.0, 0.5, 5.0759, -6.8468, -4.6185, -8.0873, -2.6135),
    "HGSE": (14.0, 460.0, 6.08, 0.0, 18.0, 0.04, 0.017, -0.42, 0.12, 5.2017, -6.5897, -4.4284, -7.6523, -2.4936),
    "HGTE": (15.0, 400.0, 6.46, 0.0, 20.0, 0.03, 0.015, -0.61, 0.1, 5.4091, -5.9729, -3.7913, -6.9007, -1.9993),

    # III–V Semiconductors
    "ALP": (7.5, 15.0, 5.46, 2.45, 10.0, 0.2, 0.05, 1.59, 2.44, 5.1769, -6.4313, -4.4894, -8.2744, -2.4365),
    "ALAS": (8.2, 30.0, 5.66, 2.16, 10.1, 0.15, 0.049, 1.39, 2.15, 5.2267, -6.2214, -4.1183, -7.8386, -2.1083),
    "ALSB": (10.2, 60.0, 6.14, 1.62, 12.0, 0.14, 0.036, 1.18, 1.83, 5.5593, -5.9163, -3.9868, -7.301, -2.1319),
    "GAP": (9.1, 15.0, 5.45, 2.26, 11.1, 0.15, 0.049, 1.61, 2.36, 5.3208, -6.562, -4.5789, -8.2171, -2.8192),
    "GAAS": (10.9, 100.0, 5.65, 1.42, 13.1, 0.067, 0.036, 0.49, 1.42, 5.4503, -6.3334, -4.4405, -7.7475, -2.7198),
    "GASB": (14.4, 200.0, 6.1, 0.73, 15.7, 0.04, 0.028, 0.11, 0.77, 5.7221, -6.0195, -4.5359, -7.2596, -2.9446),
    "INP": (9.6, 150.0, 5.87, 1.34, 12.4, 0.08, 0.042, 0.46, 1.44, 5.6309, -6.5944, -4.8483, -8.0539, -3.0678),
    "INAS": (11.8, 340.0, 6.06, 0.35, 15.0, 0.023, 0.029, -0.42, 0.35, 5.697, -6.4406, -4.8382, -7.7358, -3.1218),
    "INSB": (15.7, 650.0, 6.48, 0.17, 17.9, 0.014, 0.023, -0.61, 0.23, 5.9465, -6.184, -4.6223, -7.3335, -3.0342),

    # IV–VI Semiconductors
    "PBS": (17.2, 200.0, 5.94, 0.41, 23.0, 0.09, 0.027, 0.15, 0.65, 7.2378, -6.638, -4.3253, -8.128, -2.3724),
    "PBSE": (22.9, 460.0, 6.12, 0.27, 30.0, 0.07, 0.017, 0.05, 0.55, 7.3935, -6.5104, -4.2415, -7.8234, -2.3177),

    "DEFAULT": (1.0, 1.0, 5.0, 0.0, 1.0, 1.0, 0.02, 0.00, 0.00)

}

# Core inorganic elements for each material (ignores organic ligands like MA/FA)
MATERIAL_ELEMENTS = {
    "CSPBCL3": ["Cs", "Pb", "Cl"], "CSPBBR3": ["Cs", "Pb", "Br"], "CSPBI3":  ["Cs", "Pb", "I"],
    "MAPBI3":  ["Pb", "I"], "FAPBI3":  ["Pb", "I"], 
    "ZNS":     ["Zn", "S"], "ZNSE":    ["Zn", "Se"], "ZNTE":    ["Zn", "Te"],
    "CDS":     ["Cd", "S"], "CDSE":    ["Cd", "Se"], "CDTE":    ["Cd", "Te"],
    "HGS":     ["Hg", "S"], "HGSE":    ["Hg", "Se"], "HGTE":    ["Hg", "Te"],
    "ALP":     ["Al", "P"], "ALAS":    ["Al", "As"], "ALSB":    ["Al", "Sb"],
    "GAP":     ["Ga", "P"], "GAAS":    ["Ga", "As"], "GASB":    ["Ga", "Sb"],
    "INP":     ["In", "P"], "INAS":    ["In", "As"], "INSB":    ["In", "Sb"],
    "PBS":     ["Pb", "S"], "PBSE":    ["Pb", "Se"]
}

# Optical Refractive Indices (at optical / band-edge frequencies)
# Extracted from experimental literature and bulk eps_inf (n_r ≈ sqrt(eps_inf))
REFRACTIVE_INDEX_DICT = {
    "CS3BI2BR9": 1.97,  # sqrt(3.9)
    "CSPBCL3": 2.00,    # sqrt(4.0)
    "CSPBBR3": 2.19,    # sqrt(4.8)
    "CSPBI3": 2.26,     # sqrt(5.1)
    "MAPBI3": 2.55,     # sqrt(6.5)
    "FAPBI3": 2.49,     # sqrt(6.2)
    "ZNS": 2.26,        # sqrt(5.1)
    "ZNSE": 2.43,       # sqrt(5.9)
    "ZNTE": 2.59,       # sqrt(6.7)
    "CDS": 2.32,        # sqrt(5.4)
    "CDSE": 2.49,       # sqrt(6.2)
    "CDTE": 2.66,       # sqrt(7.1)
    "HGS": 3.36,        # sqrt(11.3)
    "HGSE": 3.74,       # sqrt(14.0)
    "HGTE": 3.87,       # sqrt(15.0)
    "ALP": 2.74,        # sqrt(7.5)
    "ALAS": 2.86,       # sqrt(8.2)
    "ALSB": 3.19,       # sqrt(10.2)
    "GAP": 3.02,        # sqrt(9.1)
    "GAAS": 3.30,       # sqrt(10.9)
    "GASB": 3.79,       # sqrt(14.4)
    "INP": 3.10,        # sqrt(9.6)
    "INAS": 3.44,       # sqrt(11.8)
    "INSB": 3.96,       # sqrt(15.7)
    "PBS": 4.15,        # sqrt(17.2)
    "PBSE": 4.79,       # sqrt(22.9)
    "DEFAULT": 2.0
}

def get_refractive_index(material_name):
    """Returns the optical refractive index n_r for a given semiconductor material."""
    mat_key = str(material_name).upper().strip() if material_name else "DEFAULT"
    if mat_key in REFRACTIVE_INDEX_DICT:
        return REFRACTIVE_INDEX_DICT[mat_key]
    if mat_key in MATERIAL_DB:
        return float(np.sqrt(MATERIAL_DB[mat_key][0]))
    return REFRACTIVE_INDEX_DICT["DEFAULT"]


def compute_radiative_rates(E_ev, f_osc, refractive_index=2.0):
    """
    Computes Einstein A spontaneous emission rates (s^-1 and fs^-1) from exciton energies (eV)
    and oscillator strengths f_osc in a dielectric medium of refractive index n_r:
      k_rad = (2 * n_r * e^4 * E^2 * f) / (4 * pi * eps_0 * m_e * c^3 * hbar^2)
            = C_rad * n_r * E^2 * f
    where C_rad = 4.3391988e7 s^-1 eV^-2 (4.3391988e-8 fs^-1 eV^-2).
    """
    C_RAD_S = 4.3391988e7  # s^-1 * eV^-2
    E_arr = np.asarray(E_ev, dtype=np.float64)
    f_arr = np.asarray(f_osc, dtype=np.float64)
    k_rad_s = C_RAD_S * refractive_index * (np.maximum(E_arr, 0.0) ** 2) * np.maximum(f_arr, 0.0)
    k_rad_fs = k_rad_s * 1e-15  # fs^-1
    return k_rad_s, k_rad_fs


def compute_energy_gap_law_rate(E_gap_ev, E_LO_ev=0.018, S_hr=1.0, A_nr=1e13):
    """
    Computes multi-phonon non-radiative recombination rate via the Englman-Jortner Energy Gap Law:
      k_nr = A_nr * exp(-gamma * (E_gap / E_LO))
    where gamma = ln(E_gap / (S * E_LO)) - 1.
    """
    if E_gap_ev <= 0.0 or E_LO_ev <= 0.0:
        return 0.0, 0.0
    num_phonons = E_gap_ev / E_LO_ev
    gamma = max(0.1, np.log(max(num_phonons / max(S_hr, 1e-3), 1.01)) - 1.0)
    exponent = -gamma * num_phonons
    exponent = max(-100.0, min(0.0, exponent))
    k_nr_s = A_nr * np.exp(exponent)
    k_nr_fs = k_nr_s * 1e-15
    return k_nr_s, k_nr_fs

def estimate_gw_qp_gap(
    coords, atom_symbols, material_name, eps_out, return_details=False,
    regularization_length_ang=1.0, residual_power=2.0, strict=False,
):
    """
    Estimate the PBE-to-QP gap correction from a finite vacuum anchor and a bulk limit.

    The leading dielectric-mismatch term scales as 1/(R + ell).  A faster-decaying
    anchor residual makes the interpolation continuous and exactly reproduces the
    finite vacuum anchor at R0.  ``ell`` and ``p`` are model parameters; one anchor
    and the bulk limit do not determine them uniquely.
    """
    if material_name is None:
        print("  [Warning] Material not specified. Cannot compute GW scaling.")
        return (None, None) if return_details else None
        
    m_name = material_name.upper()
    if m_name not in MATERIAL_DB:
        print(f"  [Warning] Material {m_name} not found in MATERIAL_DB. GW estimation failed.")
        return (None, None) if return_details else None
        
    entry = MATERIAL_DB[m_name]
    if len(entry) < 9:
        print(f"  [Warning] MATERIAL_DB entry for {m_name} is outdated. GW estimation failed.")
        return (None, None) if return_details else None
        
    # Extract Bulk Data
    eps_inf = entry[0]
    gap_pbe_bulk = entry[7]
    gap_gw_bulk = entry[8]
    
    if gap_gw_bulk == 0.0:
        print(f"  [Warning] Missing GW bulk gap for {m_name}. GW estimation failed.")
        return (None, None) if return_details else None
        
    # Extract Monomer Data (if available in the tuple)
    has_monomer_data = len(entry) >= 14
    R_mono, gap_pbe_mono, gap_gw_mono = 0.0, 0.0, 0.0
    if has_monomer_data:
        R_mono = entry[9]
        pbe_h, pbe_l = entry[10], entry[11]
        gw_h, gw_l = entry[12], entry[13]
        
        # Compute the gaps on the fly!
        gap_pbe_mono = pbe_l - pbe_h
        gap_gw_mono = gw_l - gw_h

    # Get physical size of the cluster
    metrics = get_cluster_size_metrics(coords, atom_symbols, material_name)
    R_QD_ang = metrics['R_eff_hull']
    
    # --- 1. Bulk GW Correction (Infinite Limit) ---
    delta_bulk_qp = gap_gw_bulk - gap_pbe_bulk
    
    print(f"\n  [Scaled GW Model] Quasiparticle Correction for {m_name}:")
    print(f"    Cluster Radius (R_QD) : {R_QD_ang:.3f} Å")
    anisotropy = float(metrics.get("anisotropy", 1.0))
    if anisotropy > 2.0:
        print(
            f"    [Size Warning] Principal-axis anisotropy is {anisotropy:.2f}; "
            "the scalar equivalent-volume radius may be a coarse approximation."
        )
    print(f"    Bulk PBE Gap          : {gap_pbe_bulk:.3f} eV")
    print(f"    Bulk GW Gap           : {gap_gw_bulk:.3f} eV")
    print(f"    -> Bulk Shift         : {delta_bulk_qp:+.3f} eV")
   
    ell = float(regularization_length_ang)
    p = float(residual_power)
    if ell < 0.0:
        raise ValueError("regularization_length_ang must be non-negative")
    if p <= 1.0:
        raise ValueError("residual_power must be greater than 1")

    # --- 2. Anchor-constrained finite-size correction ---
    kappa_vac = IMAGE_CHARGE_CONST_EV_ANG * (1.0 - (1.0 / eps_inf))
    kappa_solvent = IMAGE_CHARGE_CONST_EV_ANG * ((1.0 / eps_out) - (1.0 / eps_inf))
    anchor_residual = 0.0
    anchor_gap_shift = None
    radius_used = R_QD_ang

    if has_monomer_data and gap_gw_mono > 0.0:
        anchor_gap_shift = gap_gw_mono - gap_pbe_mono
        anchor_residual = (
            anchor_gap_shift - delta_bulk_qp - kappa_vac / (R_mono + ell)
        )
        if R_QD_ang < R_mono - 1.0e-8:
            message = (
                f"Target radius {R_QD_ang:.3f} Å is below the finite-anchor radius "
                f"{R_mono:.3f} Å; extrapolation is disabled."
            )
            if strict:
                raise ValueError(message)
            print(f"    [Warning] {message} Using R=R0 for the QP model.")
            radius_used = R_mono

        residual = anchor_residual * (R_mono / radius_used) ** p
        sigma_pol = kappa_solvent / (radius_used + ell) + residual
        sigma_pol_vac = kappa_vac / (radius_used + ell) + residual
        print(f"    Finite Vacuum Anchor : R0={R_mono:.3f} Å, gap shift={anchor_gap_shift:+.3f} eV")
        print(f"    Anchor Residual A    : {anchor_residual:+.3f} eV (ell={ell:.3f} Å, p={p:.3f})")
    else:
        # No finite anchor is available; retain the correct bulk and dielectric limits.
        sigma_pol = kappa_solvent / (radius_used + ell)
        sigma_pol_vac = kappa_vac / (radius_used + ell)
        print("    [Warning] No finite-QD GW anchor; using only the regularized asymptotic term.")

    print(f"    Solvent Dielectric    : eps_out = {eps_out:.2f}, eps_inf = {eps_inf:.2f}")
    print(f"    -> Polarization Shift : {sigma_pol:+.3f} eV")
 
    # --- 4. Total Quasiparticle Scissor ---
    total_scissor = delta_bulk_qp + sigma_pol
    print(f"    ==> Total GW Scissor  : {total_scissor:+.3f} eV\n")

    details = {
        "qp_model": "anchor_scaled_pbe_to_qp_model",
        "material": m_name,
        "cluster_radius_ang": float(R_QD_ang),
        "radius_definition_version": metrics.get("radius_definition_version"),
        "selected_atom_indices": metrics.get("selected_atom_indices"),
        "principal_extents_ang": metrics.get("principal_extents_ang"),
        "anisotropy_ratio": metrics.get("anisotropy_ratio"),
        "surface_offset_ang": metrics.get("surface_offset_ang"),
        "eps_out": float(eps_out),
        "eps_inf": float(eps_inf),
        "bulk_pbe_gap_ev": float(gap_pbe_bulk),
        "bulk_gw_gap_ev": float(gap_gw_bulk),
        "bulk_gw_shift_ev": float(delta_bulk_qp),
        "has_monomer_anchor": bool(has_monomer_data and gap_gw_mono > 0),
        "monomer_radius_ang": float(R_mono) if has_monomer_data else None,
        "monomer_pbe_gap_ev": float(gap_pbe_mono) if has_monomer_data else None,
        "monomer_gw_gap_ev": float(gap_gw_mono) if has_monomer_data else None,
        "anchor_pbe_homo_ev": float(pbe_h) if has_monomer_data else None,
        "anchor_pbe_lumo_ev": float(pbe_l) if has_monomer_data else None,
        "anchor_qp_homo_ev": float(gw_h) if has_monomer_data else None,
        "anchor_qp_lumo_ev": float(gw_l) if has_monomer_data else None,
        "pbe_to_qp_homo_shift_ev": float(gw_h - pbe_h) if has_monomer_data else None,
        "pbe_to_qp_lumo_shift_ev": float(gw_l - pbe_l) if has_monomer_data else None,
        "anchor_gap_shift_ev": float(anchor_gap_shift) if anchor_gap_shift is not None else None,
        "regularization_length_ang": ell,
        "residual_power": p,
        "anchor_residual_ev": float(anchor_residual),
        "radius_used_ang": float(radius_used),
        "kappa_vacuum_ev_ang": float(kappa_vac),
        "kappa_solvent_ev_ang": float(kappa_solvent),
        "finite_size_shift_vacuum_ev": float(sigma_pol_vac),
        "finite_size_shift_solvent_ev": float(sigma_pol),
        "total_scissor_vacuum_ev": float(delta_bulk_qp + sigma_pol_vac),
        "total_scissor_solvent_ev": float(total_scissor),
    }

    if return_details:
        return total_scissor, details
    return total_scissor

def compute_delta_xc(material):

    entry = MATERIAL_DB.get(material.upper(), None)

    if entry is None:
        return 0.0

    # Experimental bulk gap
    gap_exp = entry[3]

    # If PBE gap is not present return zero correction
    if len(entry) < 8:
        print(f"[Δxc] Warning: no PBE gap for {material}. Using Δxc = 0.")
        return 0.0

    gap_pbe = entry[7]

    delta_xc = gap_exp - gap_pbe

    print(f"[Δxc] Bulk correction for {material}: {delta_xc:.3f} eV")

    return max(delta_xc, 0.0)

def get_cluster_size_metrics(coords_ang, atom_symbols=None, material_name=None):
    """Return rotation/translation-invariant size metrics for selected inorganic atoms."""
    coords = np.asarray(coords_ang, dtype=float)
    selected_indices = np.arange(len(coords), dtype=int)

    if atom_symbols is not None and material_name is not None:
        m_name = material_name.upper()
        if 'MATERIAL_ELEMENTS' in globals() and m_name in MATERIAL_ELEMENTS:
            core_elements = [el.lower() for el in MATERIAL_ELEMENTS[m_name]]
            selected_indices = np.array(
                [i for i, sym in enumerate(atom_symbols) if sym.lower() in core_elements],
                dtype=int,
            )
            core_coords = coords[selected_indices]
            if len(core_coords) > 0:
                coords = np.array(core_coords)

    if len(coords) < 2:
        return {
            'R_eff_hull': 1.0, 'diameter_hull': 2.0,
            'selected_atom_indices': selected_indices.tolist(),
            'radius_definition_version': 'convex_hull_equivalent_volume_v1',
            'principal_extents_ang': [0.0, 0.0, 0.0], 'anisotropy_ratio': 1.0,
        }

    centered = coords - np.mean(coords, axis=0)
    _, _, vh = np.linalg.svd(centered, full_matrices=False)
    principal_coords = centered @ vh.T
    extents = np.ptp(principal_coords, axis=0)
    positive_extents = extents[extents > 1.0e-12]
    anisotropy = float(np.max(positive_extents) / np.min(positive_extents)) if len(positive_extents) else 1.0

    try:
        hull = ConvexHull(coords)
        volume = float(hull.volume)
        radius_geom = (3.0 * volume / (4.0 * np.pi)) ** (1.0 / 3.0)
    except Exception:
        # Degenerate (linear/coplanar) selections have no 3-D hull volume.
        radius_geom = float(np.max(np.linalg.norm(centered, axis=1)))

    # VDW_SURFACE_ANG is a diameter allowance in the legacy model; apply half once.
    surface_offset = 0.5 * VDW_SURFACE_ANG
    radius_eff = radius_geom + surface_offset
    return {
        'R_eff_hull': float(radius_eff),
        'diameter_hull': float(2.0 * radius_eff),
        'hull_volume_ang3': float(volume) if 'volume' in locals() else 0.0,
        'surface_offset_ang': float(surface_offset),
        'selected_atom_indices': selected_indices.tolist(),
        'radius_definition_version': 'convex_hull_equivalent_volume_v1',
        'principal_extents_ang': [float(x) for x in extents],
        'anisotropy_ratio': anisotropy,
    }

# =====================================================================
# Model 1: Classic MNOK Kernel (sTDA style)
# =====================================================================
def build_gamma(atom_symbols, coords, alpha, beta=0.0, eta_dict=HARDNESS_DICT):
    """
    Standard Ohno-Klopman kernel. 
    `alpha` scales the entire matrix (macroscopic screening, e.g., 1/eps_inf).
    `beta` [0.0 to 1.0] applies exact-exchange Hubbard stiffening to the diagonal.
    """
    BOHR_TO_ANG = ANG_PER_BOHR
    HA_TO_EV_val = HA_TO_EV
    coords_au = coords / BOHR_TO_ANG
    r_mat_au = squareform(pdist(coords_au))
    
    etas_ev = np.array([eta_dict.get(s.lower(), 5.0) for s in atom_symbols])
    etas_au = etas_ev / HA_TO_EV_val
    a_au = 1.0 / etas_au
    damp_mat_au = 0.5 * (a_au[:, np.newaxis] + a_au[np.newaxis, :])
    
    gamma_au = 1.0 / np.sqrt(r_mat_au**2 + damp_mat_au**2)
    gamma_ev = gamma_au * HA_TO_EV
    
    # Apply macroscopic screening
    gamma_mat = alpha * gamma_ev
    
    # Apply short-range beta stiffening to the diagonal
    if beta > 0.0:
        raise ValueError(
            "beta > 0 is disabled: the bare on-site U table has not been defined and validated"
        )
            
    return gamma_mat

# =====================================================================
# Model 2: Universal Tunable Resta-MNOK Kernel (Dual-Screening)
# =====================================================================
def build_resta_mnok(atom_symbols, coords, alpha, material_name, eps_out=2.0, eta_dict=HARDNESS_DICT):

    BOHR_TO_ANG = ANG_PER_BOHR
    HA_TO_EV_val = HA_TO_EV

    # --------------------------------------------------
    # 1. Geometry and Size Metrics
    # --------------------------------------------------
    metrics = get_cluster_size_metrics(coords, atom_symbols, material_name)
    R_QD_ang = metrics['R_eff_hull']

    m_name = material_name.upper() if material_name else "DEFAULT"
    entry = MATERIAL_DB.get(m_name, MATERIAL_DB["DEFAULT"])

    eps_inf_bulk = entry[0]   # electronic dielectric

    # --------------------------------------------------
    # 2. Core atoms for geometry
    # --------------------------------------------------
    core_coords = coords
    if m_name in MATERIAL_ELEMENTS:
        core_elements = [el.lower() for el in MATERIAL_ELEMENTS[m_name]]
        core_coords = np.array(
            [coords[i] for i, sym in enumerate(atom_symbols) if sym.lower() in core_elements]
        )

    if len(core_coords) > 1:
        r_core_ang = squareform(pdist(core_coords))
        np.fill_diagonal(r_core_ang, np.inf)
        d_NN_ang = np.median(np.min(r_core_ang, axis=1))
    else:
        d_NN_ang = 2.5

    # --------------------------------------------------
    # 3. Screening length (Thomas-Fermi / Resta Model)
    # --------------------------------------------------
    d_NN_au = d_NN_ang / BOHR_TO_ANG

    # Tie screening length to bulk dielectric response (Microscopic)
    k_s_au = np.sqrt(max(0.0, eps_inf_bulk - 1.0)) / d_NN_au
    
    # Calculate the physical screening length in Angstroms
    lambda_s_ang = (1.0 / k_s_au) * BOHR_TO_ANG if k_s_au > 0 else 0.0

    # --------------------------------------------------
    confinement_ratio = R_QD_ang / lambda_s_ang if lambda_s_ang > 0 else np.inf

    print("\n    [Kernel: Electronic Resta-MNOK]")
    print(f"    Material            = {m_name}")
    print(f"    R_QD (hull_eff)     = {R_QD_ang:.3f} Å")
    print(f"    R / lambda_s        = {confinement_ratio:.3f}")
    print(f"    epsilon_in           = {eps_inf_bulk:.3f} (electronic/high-frequency)")
    print(f"    epsilon_out          = {eps_out:.3f} (QP model only; not used in RESTA)")
    print(f"    Screening length    = {lambda_s_ang/BOHR_TO_ANG:.3f} a.u. ({lambda_s_ang:.3f} Å)")
    print()

    # --------------------------------------------------
    # 5. Build MNOK matrices
    # --------------------------------------------------
    coords_au = coords / BOHR_TO_ANG
    r_mat_au = squareform(pdist(coords_au))

    etas_au = np.array([eta_dict[s.lower()] for s in atom_symbols]) / HA_TO_EV
    a_au = 1.0 / etas_au

    damp_mat_au = 0.5 * (a_au[:, np.newaxis] + a_au[np.newaxis, :])
    mnok_denom_au = np.sqrt(r_mat_au**2 + damp_mat_au**2)

    # --------------------------------------------------
    # 6. Electronic screened direct kernel.  The environment is intentionally
    # absent here; eps_out is handled only by the QP polarization model.
    # --------------------------------------------------
    c_inf = 1.0 / eps_inf_bulk
    w_resta_au = (c_inf + (1.0 - c_inf) * np.exp(-k_s_au * r_mat_au)) / mnok_denom_au
    w_resta_ev = w_resta_au * HA_TO_EV
    # Preserve the historical two-return-value API.  Both are electronic W;
    # the first is used only by the explicitly experimental COHSEX path.
    return w_resta_ev, w_resta_ev


def estimate_brus_qp_gap(material_name, coords, atom_symbols):
    """Analytically estimates the Quantum Confined QP Gap using the Brus equation with Non-Parabolic corrections."""
    m_name = material_name.upper() if material_name else "DEFAULT"
    entry = MATERIAL_DB.get(m_name, MATERIAL_DB["DEFAULT"])
    
    E_bulk = entry[3]
    m_eff = entry[5]
    
    if E_bulk == 0.0 or m_eff == 0.0:
        print(f"  [Warning] Missing bulk gap or effective mass for {m_name}. Brus estimation failed.")
        return None
        
    metrics = get_cluster_size_metrics(coords, atom_symbols, material_name)
    R_QD_ang = metrics['R_eff_hull']
    
    # 1. Standard Parabolic Kinetic Confinement Energy
    E_conf_parabolic = (BRUS_KINETIC_EV_ANG2 * np.pi**2) / (m_eff * (R_QD_ang ** 2))
    
    # 2. Non-Parabolicity Correction (Hyperbolic Band Model)
    # Highly necessary for narrow gap materials like InAs, PbS, PbSe (E_bulk < 1.0 eV)
    if E_bulk < 2.0:
        predicted_gap = np.sqrt(E_bulk**2 + 2 * E_bulk * E_conf_parabolic)
        is_non_parabolic = True
    else:
        predicted_gap = E_bulk + E_conf_parabolic
        is_non_parabolic = False
        
    print(f"\n  [Brus Model] Estimating Confinement for {m_name}:")
    print(f"    Radius (R_QD)    : {R_QD_ang:.2f} Å")
    print(f"    Bulk Gap         : {E_bulk:.3f} eV")
    print(f"    Effective Mass   : {m_eff:.3f} m_e")
    
    if is_non_parabolic:
        print(f"    Model Used       : Hyperbolic (Non-Parabolic)")
        print(f"    Raw Parabolic dE : +{E_conf_parabolic:.3f} eV (Unphysical, applying correction...)")
    else:
        print(f"    Model Used       : Standard Parabolic")
        print(f"    Confinement (dE) : +{E_conf_parabolic:.3f} eV")
        
    print(f"    Predicted QP Gap : {predicted_gap:.3f} eV")
    
    return predicted_gap
